<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;

class Country extends Model
{
    use HasFactory;
    protected $guarded = [];


    public function cities(): HasMany
    {
        return $this->hasMany(City::class);
    }
    public function doctors(): HasManyThrough
    {
        return $this->hasManyThrough(Doctor::class, City::class);
    }


    public function getNameSymbolAttribute()
    {
        return $this->icon_symbol ." ". $this->name; // TODO: Change the autogenerated stub
    }
}
